spring:
  datasource:
    url: jdbc:mysql://106.12.29.70:3306/dzyx?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: root_123Root

debug: false
mybatis:
    type-aliases-package: com.dzyx.model
    type-handlers-package: com.dzyx.mapper
    mapper-locations: "classpath*:/mapper/*.xml"
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30

server:
   port: 8881
   
# 打印sql
logging:
 level:
    com.dzyx.mapper : debug
